DefaultContentLanguage = "en"
MetaDataFormat = "yaml"
Paginate = 2
baseURL = "https://kjcc.netlify.com"
enableRobotsTXT = true
googleAnalytics = "UA-51919693-6"
languageCode = "en-us"
newContentEditor = "atom"
preserveTaxonomyNames = true
theme = "thenewdynamic-hugo-core-theme"
title = "Nous Entertainment"
[mediaTypes."text/netlify"]
delimiter = ""
suffixes = ""
[outputFormats.HEADERS]
baseName = "_headers"
isPlainText = true
mediatype = "text/netlify"
notAlternative = true
[outputFormats.REDIR]
baseName = "_redirects"
isPlainText = true
mediatype = "text/netlify"
notAlternative = true
[outputs]
home = ["HTML", "RSS"]
page = ["HTML"]
[params]
featured_image = "/uploads/gabriele-motter-145574.jpg"
logo = "/uploads/nous-master.png"
pr_footer = "For media inquiries, please contact Amy Thompson: 202.297.3462 <amymshirk@gmail.com>"
[params.dev]
css_path = "/static/dist/css"
js_path = "/static/dist/js"
[params.styles]
body_classes = "sans-serif bg-near-white"
content_classes = "min-vh-100"
[sitemap]
changefreq = "monthly"
filename = "sitemap.xml"
priority = 0.5
[social]
twitter = ""
[taxonomies]
events = "events"
genre = "genre"
