[build]
publish = "public"
command = "HUGO_ENV=production hugo --minify"

[context]
[context.production]

[context.production.environment]
HUGO_VERSION = "0.71.1"
HUGO_ENV = "production"
NODE_ENV = "production"
GO_VERSION = "1.14"
NODE_VERSION="10.13.0"
TZ = "America/New_York"
[context.deploy-preview]
command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.71.1"
NODE_VERSION="10.13.0"
GO_VERSION = "1.14"
TZ = "America/New_York"
[context.branch-deploy]
command = "hugo --gc --minify -b $DEPLOY_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.71.1"
NODE_VERSION="10.13.0"
GO_VERSION = "1.14"
TZ = "America/New_York"
[[headers]]
for = "/*"

[headers.values]
Content-Security-Policy = "upgrade-insecure-requests"
Strict-Transport-Security = "max-age=15768000"
X-Xss-Protection = "1; mode=block"
X-Frame-Options = "DENY"
X-Content-Type-Options = "nosniff"
Referrer-Policy = "strict-origin-when-cross-origin"
Feature-Policy = "camera 'none'; geolocation 'none'; microphone 'none'"
