---
hide_body: false
fields:
- name: date
  label: Date
  type: field_group
  hidden: false
  default: {}
- name: tags
  label: Tags
  type: text
  hidden: false
  default: 
- name: images
  label: Images
  type: text
  hidden: false
  default: ''
